services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dealer_admin
      POSTGRES_PASSWORD: dealer_pass
      POSTGRES_DB: dealer_saas
    ports:
       - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: